http://localhost:3001/api/users/60d7e04f458ea2345042bd9e
Content-Type: "application/json"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZDdlZDY0YTdjNmEzMzY5YzI3ZDBlMyIsInVzZXJuYW1lIjoiQHVzZXIzIiwiaWF0IjoxNjI0NzcxNTk5LCJleHAiOjE2MjUzNzYzOTl9.wu78stofNpT76zKxITjegTPG8u7VIFY36Lt7iUY0178